theme: jekyll-theme-architect
title: Research Mode
description: Chrome Extension for automatic reader mode and key term highlighting to accelerate research. API can be found at https://github.com/kevinlu1248/researchy-api.
